version: '3.7'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: crm_dbt
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
