spring:
  cache:
    type: redis
    redis:
      host: redis
      port: 6379
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  web:
    cors:
      enabled: false
  application:
    name: crm
  #DB CONFIG
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_dbt
    username: root
    password: root
  #JPA CONFIG
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#SERVER CONFIG
server:
  port: 8089

#SECURITY
security:
  secret-key: "7MLxh2R5xz9Sttei3LRgRIDppnm9klq8BUyy/Nn2gbM="
  roles:
    user-urls: []

logging:
  level:
    root: INFO
    com.akobryn.crm: DEBUG
  file:
    name: app.log
